export class locationsMain {
    constructor(public lat?: string,   
        public lng?: string,
        public ciudad?: string,
        public titulo?:string,
        public zona?:string,
        public tempmax?:string,
        public tempmin?:string,
        public icono?:string,
        public descrip?:string,
        public diaactual?:string,
        public TEMP?:string,
        public HUME?:string,
        public VVIE?:string,
        public DVIE?:string,
        public HOY?:string,
        public PRECIPI?:string,
        public COD_DEP?:string,
        public COD_PROV?:string,
        public COD_DIST?:string,
        public descrip_abre?:string,
        public nombrestacion?:string,
        public altitud?:string,
        public distancia?:string,
        public hora?:string,
        public depestacion?:string,
        public provestacion?:string,
        public distestacion?:string,
        public AUXCOD_DEP?:string,
        public AUXCOD_PROV?:string,
        public AUXCOD_DIST?:string,
        public AUXciudad?:string
        ){}

}
